<?php

/**
 * @file
 * This is where all of the logic is kept for determining how to a views table
 * in a responsive table display.
 */


/**
 * Implementation of hook_views_api().
 */
function views_mediatable_views_api() {
  return array('api' => '3');
}

/**
 * Implementation of hook_theme().
 */
function views_mediatable_theme() {
  return array(
    'views_mediatable_table_view' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

/**
 * Theme preprocess function for views-mediatable-mediatable-table-view.tpl.php
 */
function template_preprocess_views_mediatable_table_view(&$vars) {
  $view = $vars['view'];
  $result = $view->result;

}





